services:
  - type: web
    name: bili-summarizer
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true
